apiVersion: v1
kind: Secret
metadata:
  name: file-storage-secrets
type: Opaque
stringData:
  database-url: "jdbc:postgresql://postgres-service:5432/file_storage"
  database-username: "postgres"
  database-password: "changeme"
  minio-access-key: "minioadmin"
  minio-secret-key: "changeme"
  rabbitmq-username: "admin"
  rabbitmq-password: "changeme"
  jwt-secret: "your-256-bit-secret-key-change-this-in-production"
